### ISSUE TITLE
Program doesn't start at all

### ISSUE THREAD

**Issue by nameonascreen** [CttCJim/HS2CharEdit#1]
Windows 11, Program isn't starting at all, using latest "release" with all files from release in a folder.

**Comment by nameonascreen** [comment]
also worth mentioning, i tried other versions as well.

**Comment by CttCJim** [comment]
The app is developed on Win 11, and it's working for me (obviously). It does require .Net 6.0, can you confirm that is installed? Also, can you screenshot the folder your app is in? It should look something like this: https://i.imgur.com/wVsq7Ck.png

**Comment by nameonascreen** [comment]
> The app is developed on Win 11, and it's working for me (obviously). It does require .Net 6.0, can you confirm that is installed? Also, can you screenshot the folder your app is in? It should look something like this: https://i.imgur.com/wVsq7Ck.png

Folder contains all the same files. Maybe i don't have .net installed/updated but let me check.

**Comment by nameonascreen** [comment]
> The app is developed on Win 11, and it's working for me (obviously). It does require .Net 6.0, can you confirm that is installed? Also, can you screenshot the folder your app is in? It should look something like this: https://i.imgur.com/wVsq7Ck.png

can confirm,  downloading .net 6.0 (x64) worked for me. Should list that as a requirement.
